import BaseLayout from '@/components/layout' 
import Head from 'next/head' 
import Image from 'next/image'; 
 

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Magic Movers LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout pageName="home">
        <div style={{marginTop: "50px"}}>
          <Image src="/img/comingSoon.jpg" width={400} height={200}/>
        </div>
      </BaseLayout>
    </>
  )
}
