import BaseLayout from '@/components/layout' 
import Head from 'next/head' 
import Image from 'next/image'; 
 

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Magic Movers LLC</title>
        <meta name="Magic Movers LLC" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/icon.jpg" />
      </Head>
      <BaseLayout pageName="home">
         
      </BaseLayout>
    </>
  )
}
